### ISSUE TITLE
Support multiple MC servers

### ISSUE THREAD

**Issue by CodebijSven** [sleeyax/aternos-discord-bot#49]
Hey @sleeyax  can you add, a system that you can do: /configure #channel <server><server_id>?
Thank you, for this project!

**Comment by sleeyax** [comment]
What would that do? You can restrict slash command access to a specific channel natively within discord itself.

**Comment by sleeyax** [comment]
Can one aternos account manage multiple servers?

**Comment by CodebySven** [comment]
When you create a second account, you can add that to your account!

**Comment by sleeyax** [comment]
I initially didn't plan to support multiple servers anyways because most people only have one MC server per discord server and it would make the commands more complicated to use. A feature like this would require changes to the db structure as well because only one aternos server id can be tied to one discord server at the time. 

Tbh I don't feel like adding this feature any time soon. I'm happy to accept a PR for this though. As a work around you can create another discord and set up the bot with the same credentials but different server id.

**Comment by sleeyax** [comment]
Closing this because I have no interest in adding support for this and no one else showed interest in this for a while.
